# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-01-24 14:13
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190124_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(upload_to='blog/post/%Y/%m/%d'),
        ),
    ]
